[package]
name = "wallet_behavior"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

base_types = { path = "../../../../lib/common/base_types" }
immutable_derive = { path = "../../../../lib/common/immutable_derive" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"