[package]
name = "push"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
axum = { version = "0.8.8", features = ["ws", "macros"] }
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
immutable_derive = { path = "../../../../lib/common/immutable_derive" }
chrono = "0.4.43"
# Database repository
db_repo = { path = "../../../../lib/common/db_repo" }
serde_json = "1.0.149"
rand = "0.9.2"
entity_derive = { path = "../../../../lib/common/entity_derive" }
diff = { path = "../../../../lib/common/diff" }
crossbeam-channel = "0.5.15"
parking_lot = "0.12.5"
prefetch = "0.2.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "kline_benchmark"
harness = false

[[bench]]
name = "kline_benchmark_high_freq"
harness = false

[[bench]]
name = "single_thread_kline_benchmark"
harness = false
