[package]
name = "spot_market_data_behavior"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
base_types = { path = "../../../../lib/common/base_types" }
[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

