[package]
name = "spot_behavior"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
serde = ["base_types/serde", "dep:serde", "dep:uuid"]

[dependencies]

# Clean Architecture 依赖

# LOB 仓储依赖
lob_repo = { path = "../../../../lib/common/lob_repo" }
rust_queue = { path = "../../../../lib/common/rust_queue" }

cqrs = { path = "../../../../lib/common/cqrs" }

base_types = { path = "../../../../lib/common/base_types" }

# Diff tracking
diff = { path = "../../../../lib/common/diff" }
entity_derive = { path = "../../../../lib/common/entity_derive" }
immutable_derive = { path = "../../../../lib/common/immutable_derive" }

# Database repository
db_repo = { path = "../../../../lib/common/db_repo" }

# ID generator
id_generator = { path = "../../../../lib/common/id_generator" }

# Logging
log = "0.4"

async-trait = "0.1.89"
tokio = "1.48.0"
once_cell = "1.21.3"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = "1.0"
bytes = "1.5"
uuid = { version = "1.0", features = ["v4"], optional = true }
rand = "0.9.2"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "test-util"] }
