[package]
name = "spot_proc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

# Clean Architecture 依赖
account = { path = "../../../../lib/core/account" }

# LOB 仓储依赖
lob_repo = { path = "../../../../lib/common/lob_repo" }
base_types = { path = "../../../../lib/common/base_types" }

# Diff tracking
diff = { path = "../../../../lib/common/diff" }
entity_derive = { path = "../../../../lib/common/entity_derive" }

# Database repository
db_repo = { path = "../../../../lib/common/db_repo" }

# ID generator
id_generator = { path = "../../../../lib/common/id_generator" }

# Logging
log = "0.4"

lob = { path = "../../../../lib/core/exchange/lob" }
